### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Lazorithe** [katubug/CottageWitch119#40] opened 2023-06-02 20:19 UTC
**What Cottage Witch version are you using?**
Version: 1.14.5

**What were you doing when you crashed?**
A clear and concise description of what happened.

it is unknown what happened to cause this. i know it is a storage entity issue. i have added the crash-report below

[crash-2023-06-02_19.36.40-server.txt](https://github.com/katubug/CottageWitch119/files/11638575/crash-2023-06-02_19.36.40-server.txt)

**Comment by katubug** [comment] 2023-06-03 01:05
This crash was caused by the server watchdog, which detected that a single
tick took over a minute to process. Essentially, the game lagged out.

You can disable the server watchdog by changing your server.properties file
to set the value "max-tick-time=-1". However, this won't fix whatever
lagged the server out. For that, you can use either Spark or Observable to
see what's happening on the server. Spark is accessed via /spark commands,
and Observable is accessed via the ; hotkey. Good luck!

**Closed** 2024-02-22 20:49 UTC
Labels: Crash
